runtime: nodejs16
env_variables:
  REACT_APP_API_URL: https://sigma-lyceum-374821.oa.r.appspot.com
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html